apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secret-sealed.yaml 
images:
- name: tdlinux/flask-demo
  newTag: 475dba4a4f4e262d67b4f1c4e5c5c5464f7ed42c
